import Head from "next/head";
import "./globals.css";
import { Inter } from "next/font/google";
import favicon from "./favicon.ico";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "ChatCPT App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </Head>
      <body className={inter.className}>
        <div className="bg-[#343541] ">{children}</div>
      </body>
    </html>
  );
}
