import Head from "next/head";
import "./globals.css";
import { Inter } from "next/font/google";
import Providers from "@/components/Providers";

import Login from "@/components/Login";

import SideBar from "@/components/SideBar";

import { getServerSession, unstable_getServerSession } from "next-auth/next";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import { getSession } from "next-auth/react";
import { request } from "http";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "ChatCPT App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </Head>
      <body className={`${inter.className} flex w-full`}>
        <Providers>
          <Login>{children}</Login>
        </Providers>
      </body>
    </html>
  );
}
